
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{logic-hw}[20122/05/16 LaTeX Class for PHI 134]

\LoadClass[letterpaper,10pt]{article}

\newcommand{\week}[1]{\gdef\@week{#1}}
\newcommand{\course}[1]{\gdef\@course{#1}}



% Generic Package List
\RequirePackage[utf8]{inputenc}
\RequirePackage[left=.5in,right=2.5in,top=1in,bottom=1in]{geometry}
\RequirePackage{amsmath}
\RequirePackage{amsthm}
\RequirePackage{amssymb}
\RequirePackage{ebproof}
\RequirePackage{enumitem}
\RequirePackage{setspace}
\RequirePackage{hyperref}
\RequirePackage{graphicx}
\RequirePackage{multicol}
\RequirePackage{mdframed}
\RequirePackage{xcolor, soul}
\RequirePackage{stmaryrd}
\RequirePackage[symbol]{footmisc}


